// <auto-generated />
using System;
using LazyBookworm.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LazyBookworm.Database.Migrations
{
    [DbContext(typeof(LazyBookWormContext))]
    [Migration("20220124145809_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LazyBookworm.Common.Models.UserAccount", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AccountCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 1, 24, 14, 58, 9, 502, DateTimeKind.Utc).AddTicks(3750));

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 1, 24, 14, 58, 9, 502, DateTimeKind.Utc).AddTicks(3520));

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("LazyBookworm.Common.Models.UserAccount", b =>
                {
                    b.OwnsOne("LazyBookworm.Common.Models.Common.LoginDetails", "LoginDetails", b1 =>
                        {
                            b1.Property<Guid>("UserAccountID")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Password")
                                .HasColumnType("longtext");

                            b1.Property<string>("Username")
                                .HasColumnType("longtext");

                            b1.HasKey("UserAccountID");

                            b1.ToTable("user_accounts");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountID");
                        });

                    b.OwnsOne("LazyBookworm.Common.Models.Common.Person", "PersonDetails", b1 =>
                        {
                            b1.Property<Guid>("UserAccountID")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Address")
                                .HasColumnType("longtext");

                            b1.Property<DateTime>("BirthDate")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("Country")
                                .HasColumnType("longtext");

                            b1.Property<string>("Forename")
                                .HasColumnType("longtext");

                            b1.Property<int>("Gender")
                                .HasColumnType("int");

                            b1.Property<string>("MailAddress")
                                .HasColumnType("longtext");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext");

                            b1.Property<string>("Notes")
                                .HasColumnType("longtext");

                            b1.Property<string>("Phone")
                                .HasColumnType("longtext");

                            b1.HasKey("UserAccountID");

                            b1.ToTable("user_accounts");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountID");
                        });

                    b.Navigation("LoginDetails");

                    b.Navigation("PersonDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
